AppBundle\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        UNIQ_8D93D649F85E0677:
            columns:
                - username
        UNIQ_8D93D649E7927C74:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        plainPassword:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: plain_password
    lifecycleCallbacks: {  }
